
name: Build Android APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Godot
        uses: firebelley/godot-export@v5
        with:
          godot_version: 3.5.3
          godot_download_url: https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip
          templates_download_url: https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
          base_path: .
          relative_project_path: ./
          export_debug: true
          presets: Android
          artifact_name: cadenas-rotas-apk
          export_path: build/cadenas-rotas.apk
